---
- name: webserver setup
  hosts: web
  become: yes
  tasks:
  - name: webserver installation
    dnf:
      name: httpd
      state: latest
  - name: ensure webserver is running
    service:
      name: httpd
      enabled: true
      state: started
  - name: create or update content
    copy:
      src: "var/www/html/{{ stage }}_index.html"
      dest: /var/www/html/index.html
  - name: vsftpd installation
    dnf:
      name: vsftpd
      state: latest
    when: stage == "dev"
  - name: ensure ftpserver is running
    service: 
      name: vsftpd
      state: started
      enabled: true
    when: stage == "dev" 
  