---
- name: Fill motd file with host data
  hosts: web 
  become: true
  tasks:
    - name: custom motd
      template:
        src: motd-facts.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644