---
- name: Capture Setup
  hosts: node1

  tasks:

    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        filter:
        - 'ansible_eth0'
        - 'ansible_*_mb'
      register: setup

    - debug:
        var: setup